# Generated by Django 5.2.8 on 2025-11-22 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('business_location', models.CharField(max_length=200)),
                ('business_logo', models.CharField(blank=True, help_text='Optional logo filename or URL', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_details',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=150)),
                ('cust_dob', models.DateField(blank=True, null=True)),
                ('cust_contact_number', models.CharField(max_length=20)),
                ('cust_companion', models.CharField(blank=True, help_text='Name of person accompanying the customer', max_length=150)),
                ('cust_companion_relation', models.CharField(blank=True, help_text='Relation of companion to the customer', max_length=100)),
                ('cust_visit_purpose', models.CharField(help_text='Purpose of visit (e.g., Fever, Checkup, Follow-up)', max_length=200)),
                ('cust_notes', models.TextField(blank=True, help_text='Additional notes about the visit')),
                ('cust_walkin_date', models.DateField()),
                ('cust_clockin', models.TimeField()),
                ('cust_clockout', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='walkinplus_app.businessdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_details',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Contact Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
