# Generated by Django 5.2.8 on 2025-11-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkinplus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
